DEFAULT_HTTP_PORT = 8007
DEFAULT_HTTP_HOST = "127.0.0.1"
DEFAULT_HTTP_ROOT = "http://%s:%s/" % (DEFAULT_HTTP_HOST, DEFAULT_HTTP_PORT)
DEFAULT_POST_MESSAGE_URL = DEFAULT_HTTP_ROOT + "post_message"

DEFAULT_MQTT_HOST = "localhost"
DEFAULT_MQTT_PORT = 1883
DEFAULT_MQTT_TOPIC = "messagebus"

CONFIG_ROOT = "config"


